threadInTaskInit
lhr-solar/BPS pull request #233
Opened 2020-10-17 20:07 UTC by alekxoo

2020-11-07 20:28 UTC, manthanand commented on Apps/Src/Task_Init.c
> +				&err);					// return err code}
This thread should destroy itself after it is done.

2020-11-07 20:29 UTC, manthanand commented on Apps/Src/Task_Init.c
> +    OSSemCreate(&Fault_Sem4,
Why is this not safety check sem4?

2020-11-07 20:34 UTC, manthanand commented on Apps/Src/Task_Init.c
> +    	OSTaskCreate(&Init_TCB,				// TCB
Why are these all Init_TCB, they should all be TCB's for their own thread. These are all listed in Tasks.c

2020-11-07 20:40 UTC, manthanand commented on Apps/Src/Task_Init.c
> +				Init_Stk,				// Stack
They also all have their own stack sizes.

2020-11-12 18:34 UTC, ClarkPoon requested changes

2020-11-14 23:23 UTC, ClarkPoon reviewed
Do you know how to get rid of the changes to the submodules, or should I do that?

2020-11-14 23:23 UTC, ClarkPoon commented on Apps/Src/Task_Init.c
>      // TODO: Initialize threads! Look at main.c for reference
We should remove this comment, since it has already been done

2020-11-14 23:27 UTC, manthanand commented
I think we need those changes to the submodules in order for the code to work

2020-11-16 17:01 UTC, ClarkPoon commented
> I think we need those changes to the submodules in order for the code to work

Yeah, you're right

2020-11-16 17:01 UTC, merged