Added undervoltage cutoff detection for charging
lhr-solar/BPS pull request #246
Opened 2020-11-14 22:13 UTC by manthanand

2020-11-14 23:13 UTC, ClarkPoon requested changes
Can you get rid of the changes to the submodules, or should I do that?

2020-11-14 23:13 UTC, ClarkPoon commented on Apps/Src/Voltage.c
> +		if (Current_IsCharging){
Shouldn't this be `if (Current_IsCharging()){`

2020-11-14 23:24 UTC, manthanand commented
I don't think it'll let me do it so you probably should.

2020-11-16 17:04 UTC, ClarkPoon approved these changes
After a second look, the changes to the submodules in here are correct

2020-11-16 17:04 UTC, merged