Finished CANBSP Documentation
lhr-solar/BPS pull request #284
Opened 2021-01-16 19:24 UTC by manthanand

2021-01-16 21:44 UTC, sugamarora99 commented on Docs/source/Software/BSP.rst
> +    and post must occur before and after the functions are called.
Pend and post for what resource?

2021-01-16 21:49 UTC, sugamarora99 approved these changes

2021-01-16 22:20 UTC, ClarkPoon requested changes

2021-01-16 22:20 UTC, ClarkPoon commented on Docs/source/Software/BSP.rst
> +    outside the file.
I think it would make more sense to not put anything about the queue in here. I would instead put it in additional considerations

2021-01-19 00:47 UTC, ClarkPoon approved these changes

2021-01-19 00:50 UTC, ClarkPoon approved these changes

2021-01-19 00:51 UTC, merged