Temperature App Documentation
lhr-solar/BPS pull request #302
Opened 2021-01-23 22:14 UTC by sugamarora99

2021-01-23 22:17 UTC, manthanand submitted a review, later dismissed

2021-01-24 22:08 UTC, ClarkPoon requested changes

2021-01-24 22:08 UTC, ClarkPoon commented on Docs/source/Software/Apps.rst
> +    This file uses a global ``int32_t ModuleTemperatures[][]`` 2D array that contains each sensor's temperature.
I think it is important to note that you should call ``Temperature_UpdateAllMeasurements()`` to update this array. For example, it is not obvious from reading the header file that you need to call this function to get the data that ``Temperature_CheckStatus()`` uses.

2021-01-30 17:38 UTC, ClarkPoon submitted a review, later dismissed

2021-01-30 17:39 UTC, ClarkPoon approved these changes

2021-01-30 17:45 UTC, merged