Software Overview Docs
lhr-solar/BPS pull request #341
Opened 2021-02-27 21:07 UTC by sugamarora99

2021-02-27 21:32 UTC, manthanand commented on Docs/source/Overview/software-overview.rst
> +- CAN
I would add the :term: syntax here

2021-02-27 21:32 UTC, manthanand commented on Docs/source/Overview/software-overview.rst
> +The RTOS uses a scheduler to run multiple threads.
Add :term: here for RTOS

2021-02-27 21:33 UTC, manthanand commented on Docs/source/Overview/software-overview.rst
> +Descriptions of what each task does can be found in the Tasks section.
I would hyperlink to the tasks section for each task above. :rref:

2021-03-06 22:45 UTC, ClarkPoon requested changes

2021-03-06 22:45 UTC, ClarkPoon commented on Docs/source/Overview/software-overview.rst
> +Running these threads creates "psuedo-concurrency".
```suggestion
Running these threads creates "pseudo-concurrency".
```

2021-03-06 22:45 UTC, ClarkPoon commented on Docs/source/Overview/software-overview.rst
> +- :ref:`Idle <Idle Task>`
Can we add priority numbers to these, or make it clear that these are sorted by priority?

2021-03-06 22:45 UTC, ClarkPoon commented on Docs/source/Overview/software-overview.rst
> +We use the Micrium uC/OS-III RTOS.
I think it would be nice if we linked to the Micrium Docs here

2021-03-08 22:39 UTC, ClarkPoon approved these changes

2021-03-08 22:40 UTC, merged