Mutexpend update references
lhr-solar/BPS pull request #497
Opened 2022-10-08 21:11 UTC by ray4477

# Quality Assurance Checklist 
To make reviews more efficient, please make sure the software feature meets the following standards and check everything off that meets the quality check. Once everything has been checked, the assigned reviewers will begin the review process. _Edit this description to check off the list._

There are exceptions with all guidelines. As long as your decisions are justified, then you are good! Contact the reviewers or the leads about any exceptions. 

## Requirements 
- [ ] Followed Coding Style Guide 
- [ ] Code Build checks pass 
- [ ] No merge conflicts 
- [ ] Software feature has test associated with it. 
- [ ] Software feature has documentation for it updated.
- [ ] Test provides useful information and uses relevant data to accurately represent BPS 
    - NOTE: If test file already exists, use that one 
- [ ] 2 Members of the team have already reviewed my PR 
    - NOTE: Approver will not look at PR if 2 other members haven't reviewed first 
- [ ] Did you Have Fun?

## Things to Consider 
- [ ] Even if the above are checked, is this the best way of writing my code? 
    - It's possible to write code that works, but are there ways to make code more efficient?

2022-10-09 21:10 UTC, connorl309 approved these changes
Don't see any issues here with the replacements. Not sure how we'll write test files for RTOS changes though.

2022-10-15 18:12 UTC, ClarkPoon commented
> # Quality Assurance Checklist
> 
> To make reviews more efficient, please make sure the software feature meets the following standards and check everything off that meets the quality check. Once everything has been checked, the assigned reviewers will begin the review process. _Edit this description to check off the list._
> 
> There are exceptions with all guidelines. As long as your decisions are justified, then you are good! Contact the reviewers or the leads about any exceptions.
> ## Requirements
> 
>     * [x]  Followed Coding Style Guide
> 
>     * [x]  Code Build checks pass
> 
>     * [x]  No merge conflicts
> 
>     * [x]  Software feature has test associated with it.
> 
>     * [x]  Software feature has documentation for it updated.
> 
>     * [x]  Test provides useful information and uses relevant data to accurately represent BPS
>       
>       * NOTE: If test file already exists, use that one
> 
>     * [x]  2 Members of the team have already reviewed my PR
>       
>       * NOTE: Approver will not look at PR if 2 other members haven't reviewed first
> 
>     * [x]  Did you Have Fun?
> 
> 
> ## Things to Consider
> 
>     * [x]  Even if the above are checked, is this the best way of writing my code?
>       
>       * It's possible to write code that works, but are there ways to make code more efficient?

Can you also put what the pull request does (and why we want to do this) in the description? This makes it easier to review, and if in the future we see this commit and want to know what it is for, it is easier to figure it out.

2022-10-15 18:19 UTC, ClarkPoon requested changes

2022-10-15 18:19 UTC, ClarkPoon commented on Apps/Src/CAN_Queue.c
> +    RTOS_BPS_MutexPend(&canFifo_Mutex, 0, OS_OPT_POST_NONE);
Lmao I just realized we've been calling it like this the whole time and `OS_OPT_POST_NONE` isn't evan a valid option for `OSMutexPend`. See the micrium docs here for the proper options: [https://docs.silabs.com/micrium/latest/micrium-kernel-api/05-kernel-mutex-api#os-mutex-pend](https://docs.silabs.com/micrium/latest/micrium-kernel-api/05-kernel-mutex-api#os-mutex-pend). I think we probably want to use `OS_OPT_PEND_BLOCKING` for everything

2022-10-15 18:19 UTC, ClarkPoon commented on Tests/Test_WD_Task.c
> +        RTOS_BPS_MutexPend(&WDog_Mutex, 0, OS_OPT_PEND_BLOCKING);
I think we always pass `0` as the second parameter, so you can remove it and just pass it internally

2022-10-17 19:23 UTC, manthanand commented on Drivers/Src/CANbus.c
> +	RTOS_BPS_MutexPend(&CANbus_TxMutex,
Try to follow coding styles guide by keeping all of them same format.

2022-10-17 19:23 UTC, manthanand commented on Drivers/Src/CANbus.c
> +	RTOS_BPS_MutexPend(&CANbus_RxMutex,
Same here.

2022-10-18 18:32 UTC, manthanand approved these changes

2022-10-18 18:33 UTC, merged